### PR TITLE
Add a 'bespoke-current' class to the current bullet

### PR DESCRIPTION
**Pull request by pimterry**
It's quite useful to be able to style the currently selected 'newest' bullet different to the others, which isn't currently possible. This very simply adds that, which a whole bunch of tests for it to boot.

### CODE REVIEW

**Comment by pimterry** [comment]
This is failing on `npm install`, and I haven't touched package.json, so it's not me. Not totally clear to me why it's failing (worked locally for me yesterday), but I expect it's probably spurious; if you rerun it it'll work it out.

**Comment by pimterry** [comment]
Nudge.

**Comment by markdalgleish** [comment]
This is a great idea :) I've overhauled all the plugins recently to target usage with Browserify, so things have changed a little bit. Would you be able to update your pull request to match what's currently in master? This will also fix issues with the Travis build failing.

**Comment by pimterry** [comment]
I've now rebased this on top of your changes and the build's passing. Ready to merge?

**Comment by markdalgleish** [comment]
Awesome work, thank you! :+1:

**Pull request merged**
